name: digia_inspector
description: A comprehensive debug console for Digia applications, providing real-time logging of network requests, state changes, and application events with an intuitive UI.
version: 1.0.0
homepage: https://www.digia.tech
repository: https://github.com/Digia-Technology-Private-Limited/digia_inspector
issue_tracker: https://github.com/Digia-Technology-Private-Limited/digia_inspector/issues
documentation: https://docs.digia.tech
topics:
  [
    debugging,
    logging,
    monitoring,
    networking,
    observability,
  ]

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:

  digia_inspector_core: ^1.0.0

  # digia_inspector_core:
  #   git:
  #     url: git@github.com:Digia-Technology-Private-Limited/digia_inspector_core.git
  #     ref: main

  dio: ^5.9.0
  flutter:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
