name: digia_inspector
description: A debug console for Digia apps, providing real-time logging of network requests, actions, and states.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  digia_inspector_core:
    git:
      url: git@github.com:Digia-Technology-Private-Limited/digia_inspector_core.git
      ref: main
  dio: ^5.9.0
  flutter:
    sdk: flutter
  multi_split_view: ^3.6.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
